/**
 * In-memory reducer for the Budget module (Outil Budget). Holds seasons,
 * drafts, pooled team-groups and budget lines. All mutations flow through here
 * so create / edit / delete / validate / duplicate persist across navigation.
 *
 * IDs and timestamps are generated by the action CREATORS (DataProvider) and
 * passed in, keeping this reducer a pure function of (state, action). The only
 * exception is the clone operations (duplicate / import), which mint child ids
 * with crypto.randomUUID() while remapping references — done here because they
 * need to walk the current state.
 */

import {
  budget2DraftsSeed,
  budget2GroupsSeed,
  budget2LinesSeed,
  budget2SeasonsSeed,
  type BudgetLine,
  type BudgetTeamGroup,
  type Budget2Draft,
  type Budget2Season,
} from "@/data/seed/budget2"

export type Budget2State = {
  seasons: Budget2Season[]
  drafts: Budget2Draft[]
  groups: BudgetTeamGroup[]
  lines: BudgetLine[]
}

export const budget2InitialState: Budget2State = {
  seasons: budget2SeasonsSeed,
  drafts: budget2DraftsSeed,
  groups: budget2GroupsSeed,
  lines: budget2LinesSeed,
}

export type Budget2Action =
  | { type: "addSeason"; season: Budget2Season }
  | { type: "addDraft"; draft: Budget2Draft }
  | { type: "updateDraft"; id: string; patch: Partial<Budget2Draft>; at: string }
  | { type: "removeDraft"; id: string }
  | { type: "duplicateDraft"; id: string; newId: string; at: string }
  | { type: "validateDraft"; id: string; at: string }
  | {
      type: "importFromDraft"
      sourceId: string
      targetId: string
      mode: "replace" | "append"
      at: string
    }
  | { type: "addLine"; line: BudgetLine; at: string }
  | { type: "updateLine"; id: string; patch: Partial<BudgetLine>; at: string }
  | { type: "removeLine"; id: string; at: string }
  | { type: "addGroup"; group: BudgetTeamGroup; at: string }
  | { type: "updateGroup"; id: string; patch: Partial<BudgetTeamGroup>; at: string }
  | { type: "removeGroup"; id: string; at: string }

/** Stamp a draft's updated_at (dernière modification) after a child mutation. */
function touch(drafts: Budget2Draft[], draftId: string | undefined, at: string) {
  if (!draftId) return drafts
  return drafts.map((d) => (d.id === draftId ? { ...d, updated_at: at } : d))
}

export function budget2Reducer(
  state: Budget2State,
  action: Budget2Action,
): Budget2State {
  switch (action.type) {
    case "addSeason":
      return { ...state, seasons: [...state.seasons, action.season] }

    case "addDraft":
      return { ...state, drafts: [action.draft, ...state.drafts] }

    case "updateDraft":
      return {
        ...state,
        drafts: state.drafts.map((d) =>
          d.id === action.id
            ? { ...d, ...action.patch, updated_at: action.at }
            : d,
        ),
      }

    case "removeDraft":
      return {
        ...state,
        drafts: state.drafts.filter((d) => d.id !== action.id),
        groups: state.groups.filter((g) => g.draft_id !== action.id),
        lines: state.lines.filter((l) => l.draft_id !== action.id),
      }

    case "duplicateDraft": {
      const src = state.drafts.find((d) => d.id === action.id)
      if (!src) return state
      const clone: Budget2Draft = {
        id: action.newId,
        season_id: src.season_id,
        label: `${src.label} (copie)`,
        status: "brouillon",
        updated_at: action.at,
      }
      // remap groups (new ids), then remap the lines' group_ref through the map
      const groupMap = new Map<string, string>()
      const newGroups = state.groups
        .filter((g) => g.draft_id === action.id)
        .map((g) => {
          const id = crypto.randomUUID()
          groupMap.set(g.id, id)
          return { ...g, id, draft_id: action.newId }
        })
      const newLines = state.lines
        .filter((l) => l.draft_id === action.id)
        .map((l) => ({
          ...l,
          id: crypto.randomUUID(),
          draft_id: action.newId,
          group_ref: l.group_ref ? groupMap.get(l.group_ref) : undefined,
        }))
      return {
        ...state,
        drafts: [clone, ...state.drafts],
        groups: [...state.groups, ...newGroups],
        lines: [...state.lines, ...newLines],
      }
    }

    case "validateDraft": {
      const target = state.drafts.find((d) => d.id === action.id)
      if (!target) return state
      return {
        ...state,
        drafts: state.drafts.map((d) => {
          if (d.id === action.id)
            return { ...d, status: "valide", validated_at: action.at, updated_at: action.at }
          // demote the previous reference of the same season
          if (d.season_id === target.season_id && d.status === "valide")
            return { ...d, status: "archive", updated_at: action.at }
          return d
        }),
      }
    }

    case "importFromDraft": {
      const groupMap = new Map<string, string>()
      const importedGroups = state.groups
        .filter((g) => g.draft_id === action.sourceId)
        .map((g) => {
          const id = crypto.randomUUID()
          groupMap.set(g.id, id)
          return { ...g, id, draft_id: action.targetId }
        })
      const importedLines = state.lines
        .filter((l) => l.draft_id === action.sourceId)
        .map((l) => ({
          ...l,
          id: crypto.randomUUID(),
          draft_id: action.targetId,
          group_ref: l.group_ref ? groupMap.get(l.group_ref) : undefined,
        }))
      const keepGroups =
        action.mode === "replace"
          ? state.groups.filter((g) => g.draft_id !== action.targetId)
          : state.groups
      const keepLines =
        action.mode === "replace"
          ? state.lines.filter((l) => l.draft_id !== action.targetId)
          : state.lines
      return {
        ...state,
        groups: [...keepGroups, ...importedGroups],
        lines: [...keepLines, ...importedLines],
        drafts: touch(state.drafts, action.targetId, action.at),
      }
    }

    case "addLine":
      return {
        ...state,
        lines: [...state.lines, action.line],
        drafts: touch(state.drafts, action.line.draft_id, action.at),
      }

    case "updateLine": {
      const line = state.lines.find((l) => l.id === action.id)
      return {
        ...state,
        lines: state.lines.map((l) =>
          l.id === action.id ? { ...l, ...action.patch } : l,
        ),
        drafts: touch(state.drafts, line?.draft_id, action.at),
      }
    }

    case "removeLine": {
      const line = state.lines.find((l) => l.id === action.id)
      return {
        ...state,
        lines: state.lines.filter((l) => l.id !== action.id),
        drafts: touch(state.drafts, line?.draft_id, action.at),
      }
    }

    case "addGroup":
      return {
        ...state,
        groups: [...state.groups, action.group],
        drafts: touch(state.drafts, action.group.draft_id, action.at),
      }

    case "updateGroup": {
      const grp = state.groups.find((g) => g.id === action.id)
      return {
        ...state,
        groups: state.groups.map((g) =>
          g.id === action.id ? { ...g, ...action.patch } : g,
        ),
        drafts: touch(state.drafts, grp?.draft_id, action.at),
      }
    }

    case "removeGroup": {
      const grp = state.groups.find((g) => g.id === action.id)
      return {
        ...state,
        groups: state.groups.filter((g) => g.id !== action.id),
        // its pooled lines go with it
        lines: state.lines.filter((l) => l.group_ref !== action.id),
        drafts: touch(state.drafts, grp?.draft_id, action.at),
      }
    }

    default:
      return state
  }
}
